# Generated by Django 4.2.27 on 2026-01-09 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('photo', models.ImageField(upload_to='staff/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('instagram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('working_hours', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialization', models.ManyToManyField(related_name='specialists', to='services.servicecategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Staff',
                'ordering': ['display_order', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='StaffService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, help_text='Custom price for this staff member (optional)', max_digits=8, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_services', to='services.service')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_services', to='staff.staff')),
            ],
            options={
                'ordering': ['service__name'],
                'unique_together': {('staff', 'service')},
            },
        ),
        migrations.CreateModel(
            name='StaffPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary/favorite stylist')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_clients', to='staff.staff')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stylist_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
                'unique_together': {('user', 'staff')},
            },
        ),
        migrations.CreateModel(
            name='StaffAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='staff.staff')),
            ],
            options={
                'verbose_name_plural': 'Staff Availabilities',
                'ordering': ['date', 'start_time'],
                'unique_together': {('staff', 'date', 'start_time', 'end_time')},
            },
        ),
    ]
